CREATE DATABASE IF NOT EXISTS php_todo;

USE php_todo;

CREATE TABLE IF NOT EXISTS todos (
  id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  description VARCHAR(255) NOT NULL,
  done TINYINT(1) DEFAULT 0
);
